version = 0.1

[default.global.parameters]
stack_name = "habit-tracker"
region = "us-east-2"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-2"
s3_prefix = "habit-tracker"
parameter_overrides = "GoogleClientId=\"288347590774-fkhioghvihmnbrh45vqi6dq39t42ga93.apps.googleusercontent.com\" AllowedOrigin=\"http://localhost:3002\""
image_repositories = []
